version: 2.1

executors:
  node-docker-container:
    docker:
      - image: cimg/node:18.9.1

commands:
  test-command:
    steps:
      - checkout
      - run:
          name: Test step
          command: |
            echo "Hello"
            circleci-agent step halt
      - run:
          name: Variable test step
          command: |
            X="test"
            [ -z "$X" ] && echo "Empty" && exit
            echo ""
      - run:
          name: Additional step
          command: |
            echo "Additional"


jobs:
  test-job:
    executor: node-docker-container
    steps:
      - test-command


workflows:
  test-workflow:
    jobs:
      - test-job
